from logic import TruthTable
myTable = TruthTable(['-a'])
myTable.display()
print("")
print("")
myTable2 = TruthTable(['a or b'])
myTable2.display()
print("")
print("")
myTable3 = TruthTable(['a and b'])
myTable3.display()
print("")
print("")
myTable4= TruthTable(['a -> b'])
myTable4.display()
print("")
print("")
myTable5 = TruthTable(['a <-> b'])
myTable5.display()

